# Generated by Django 5.2.7 on 2025-10-09 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_snapshot', models.TextField(help_text='Snapshot serializado do perfil (JSON string)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='ID do filme vindo da API externa', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('rank', models.PositiveSmallIntegerField(help_text='Posição (1, 2, ou 3) do filme dentro do seu humor')),
                ('movie_metadata', models.TextField(help_text='Metadados serializados (JSON string)')),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='recommendations.mood')),
                ('recommendation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendationset')),
            ],
        ),
        migrations.CreateModel(
            name='ShownHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField(blank=True, help_text='Contexto serializado (JSON string)')),
                ('mood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.mood')),
                ('recommendation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendationitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubMood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submoods', to='recommendations.mood')),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ProfileGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.genre')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'genre')},
            },
        ),
    ]
