# Generated by Django 5.1.4 on 2025-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_populate_initial_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationitem',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL do pôster do filme', max_length=500, null=True),
        ),
    ]
