# Generated by Django 5.2.7 on 2025-10-09 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('attribute', models.CharField(choices=[('openness', 'Abertura'), ('conscientiousness', 'Conscienciosidade'), ('extraversion', 'Extroversão'), ('agreeableness', 'Amabilidade'), ('neuroticism', 'Neuroticismo')], help_text='O traço de personalidade que esta pergunta avalia', max_length=20)),
                ('first_alternative', models.CharField(max_length=255)),
                ('first_alternative_value', models.IntegerField()),
                ('second_alternative', models.CharField(max_length=255)),
                ('second_alternative_value', models.IntegerField()),
                ('third_alternative', models.CharField(max_length=255)),
                ('third_alternative_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openness', models.FloatField(default=0.0, help_text='Abertura a novas experiências')),
                ('conscientiousness', models.FloatField(default=0.0, help_text='Nível de organização e disciplina')),
                ('extraversion', models.FloatField(default=0.0, help_text='Nível de sociabilidade')),
                ('agreeableness', models.FloatField(default=0.0, help_text='Nível de empatia e cooperação')),
                ('neuroticism', models.FloatField(default=0.0, help_text='Instabilidade emocional')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.question')),
            ],
            options={
                'unique_together': {('profile', 'question')},
            },
        ),
    ]
